import React from 'react';
import { Link } from 'react-router-dom';
import { ArrowLeft } from 'lucide-react';
import { SEO } from '../components/SEO';

export default function TermsOfService() {
  return (
    <div className="min-h-screen bg-gray-50 text-gray-800 font-sans p-6 md:p-12">
      <SEO
        title="Terms of Service"
        description="Review the SocialMock terms of service and acceptable-use guidelines."
        canonical="/terms"
      />
      <div className="max-w-3xl mx-auto bg-white p-8 md:p-12 rounded-3xl shadow-xl border border-gray-100">
        <Link to="/" className="inline-flex items-center text-indigo-600 hover:text-indigo-800 font-medium mb-8 transition-colors">
          <ArrowLeft className="w-4 h-4 mr-2" /> Back to Home
        </Link>
        <h1 className="text-4xl font-extrabold mb-4">Terms of Service</h1>
        <p className="text-gray-500 mb-8 font-medium">Last updated: {new Date().toLocaleDateString()}</p>
        
        <div className="space-y-8 text-gray-700 leading-relaxed text-lg">
          <section>
            <h2 className="text-2xl font-bold text-gray-900 mb-3">1. Acceptance of Terms</h2>
            <p className="bg-gray-50 p-4 rounded-xl text-gray-600 border border-gray-100">By using this website, you agree to these Terms of Service. This application is provided "as is" and is intended solely for fun, parody, and entertainment purposes. There is absolutely no intention for harm or any malicious activities.</p>
          </section>

          <section>
            <h2 className="text-2xl font-bold text-gray-900 mb-3">2. Acceptable Use</h2>
            <p>You agree to use this tool responsibly and ethically. You must NOT use the mockups generated here to:</p>
            <ul className="list-disc pl-6 mt-4 space-y-2 bg-red-50 text-red-900 p-6 rounded-xl border border-red-100">
              <li>Defame, harass, bully, or harm any individual or organization.</li>
              <li>Spread fake news, misinformation, or malicious propaganda.</li>
              <li>Commit fraud, identity theft, or deceptive practices.</li>
              <li>Create illegal or abusive content.</li>
            </ul>
          </section>

          <section>
            <h2 className="text-2xl font-bold text-gray-900 mb-3">3. Disclaimer of Liability</h2>
            <p>The creators of this website hold no responsibility for the content generated by users. We simply provide the aesthetic canvas. You are solely and fully responsible for how you distribute and use the output generated with this tool.</p>
          </section>

          <section>
            <h2 className="text-2xl font-bold text-gray-900 mb-3">4. Intellectual Property</h2>
            <p>This service parodies popular UI designs. All product names, logos, brands, and layouts are property of their respective owners. Their use here is purely for functional parody and context, and does not imply any affiliation with or endorsement by them.</p>
          </section>
        </div>
      </div>
    </div>
  );
}
